# Generated by Django 4.2.6 on 2023-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lockers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locker',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
