# Generated by Django 4.2.7 on 2023-11-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lockers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('product_height', models.IntegerField(default=0)),
                ('product_width', models.IntegerField(default=0)),
                ('code', models.CharField(default='', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LockerBridge.client')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lockers.locker')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LockerBridge.operator')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lockers.station')),
            ],
        ),
        migrations.CreateModel(
            name='Retrieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieved_date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LockerBridge.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Loaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LockerBridge.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LockerBridge.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='CancelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=200)),
                ('cancel_date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LockerBridge.reservation')),
            ],
        ),
    ]
